### ISSUE TITLE
Integrar Preview interactiva de carreras

### ISSUE THREAD

**Issue by NicoHalpe** [pmemoli/Machete-Exactas-Front#3]
En las previews de las carreras se puede poner un iframe a https://planes.nicohalpe.com.ar/?preview&preview-name=Licenciatura%20en%20Ciencias%20de%20la%20Computaci%C3%B3n

(Habría que agregar las demás carreras, por ahora metí compu y datos)

**Comment by nachovigilante** [comment]
Buenas Nico, tengo un fork del repo en donde estoy integrando estos mismos grafos que planteás dentro de la misma página, estate atento para cuando lo mergeemos así si tenés algo para aportar sobre eso los podés hacer ahí.

**Comment by pmemoli** [comment]
ahi mergie los cambios que propuso nacho
